package require -exact qsys 12.1

set_validation_property AUTOMATIC_VALIDATION false

add_instance CLMonteTransport_system CLMonteTransport_system

add_connection acl_iface.kernel_clk CLMonteTransport_system.clock_reset
add_connection acl_iface.kernel_clk2x CLMonteTransport_system.clock_reset2x
add_connection acl_iface.kernel_reset CLMonteTransport_system.clock_reset_reset

add_connection CLMonteTransport_system.avm_memgmem0_port_0_0_rw acl_iface.kernel_mem0
add_connection CLMonteTransport_system.avm_memgmem0_port_1_0_rw acl_iface.kernel_mem1


add_connection acl_iface.kernel_irq CLMonteTransport_system.kernel_irq

add_connection acl_iface.kernel_cra CLMonteTransport_system.avs_MCd_cra
set_connection_parameter_value acl_iface.kernel_cra/CLMonteTransport_system.avs_MCd_cra baseAddress "0x0"


save_system

